// SPDX-License-Identifier: Apache-2.0 OR MIT

package xorg

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/Mr-Tao/libinput-curve/internal/config"
)

func Render(cfg *config.Config, overrides config.ScaleOverrides) (string, error) {
	if cfg == nil {
		return "", fmt.Errorf("xorg: nil config")
	}
	if err := cfg.Validate(); err != nil {
		return "", err
	}

	seenHardwareIDs := make(map[string]string)
	var output strings.Builder
	output.WriteString("# Generated by libinput-curve. Local edits will be overwritten.\n\n")
	for _, rule := range cfg.Devices {
		hardwareID := rule.Match.NormalizedHardwareID()
		if hardwareID == "" {
			return "", fmt.Errorf(
				"xorg: rule %q needs vendor_id and product_id for persistent matching",
				rule.ID,
			)
		}
		if rule.Match.NameRegex != "" {
			return "", fmt.Errorf(
				"xorg: rule %q uses name_regex, which cannot be translated to MatchProduct; use product_contains",
				rule.ID,
			)
		}
		if previous, ok := seenHardwareIDs[hardwareID]; ok {
			return "", fmt.Errorf(
				"xorg: rules %q and %q share MatchUSBID %s",
				previous,
				rule.ID,
				hardwareID,
			)
		}
		seenHardwareIDs[hardwareID] = rule.ID

		profile, err := cfg.ProfileScaled(rule, overrides)
		if err != nil {
			return "", err
		}

		fmt.Fprintf(&output, "Section \"InputClass\"\n")
		fmt.Fprintf(&output, "    Identifier \"libinput-curve-%s\"\n", rule.ID)
		output.WriteString("    MatchDriver \"libinput\"\n")
		output.WriteString("    MatchIsPointer \"true\"\n")
		fmt.Fprintf(&output, "    MatchUSBID \"%s\"\n", hardwareID)
		if rule.Match.ProductContains != "" {
			fmt.Fprintf(
				&output,
				"    MatchProduct \"%s\"\n",
				rule.Match.ProductContains,
			)
		}
		output.WriteString("\n")
		output.WriteString("    Option \"AccelProfile\" \"custom\"\n")
		writeCurve(&output, "Fallback", profile.Fallback)
		writeCurve(&output, "Motion", profile.Motion)
		writeCurve(&output, "Scroll", profile.Scroll)
		output.WriteString("EndSection\n\n")
	}
	return output.String(), nil
}

func writeCurve(output *strings.Builder, name string, curve *config.Curve) {
	if curve == nil {
		return
	}
	points := make([]string, len(curve.Points))
	for index, point := range curve.Points {
		points[index] = formatFloat(point)
	}
	fmt.Fprintf(
		output,
		"    Option \"AccelPoints%s\" \"%s\"\n",
		name,
		strings.Join(points, " "),
	)
	fmt.Fprintf(
		output,
		"    Option \"AccelStep%s\" \"%s\"\n",
		name,
		formatFloat(curve.Step),
	)
}

func formatFloat(value float64) string {
	return strconv.FormatFloat(value, 'f', 6, 64)
}
